export const CHANGE_CATEGORY ="CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS ="GET_CATEGORIES_SUCCESS"

export const GET_STUDENT_LIST ="GET_STUDENT_LIST"
export const GET_COURSE_LIST ="GET_COURSE_LIST"
export const GET_CLASSROOM_LIST="GET_CLASSROOM_LIST"
export const GET_LECTURER_LIST="GET_LECTURER_LIST"
export const GET_BOOK_LIST="GET_BOOK_LIST"

export const POST_STUDENT_ADD="POST_STUDENT_ADD"
export const DELETE_STUDENT="DELETE_STUDENT"
export const UPDATE_STUDENT="UPDATE_STUDENT"